name: pagamentos_app
description: App de controle de pagamentos mensais
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1

flutter:
  uses-material-design: true
